name: staging-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - pip=26.0.1
  - python=3.12.13
  - conda-forge::ome-types=0.5.2
  - numpy=1.26.4
  - conda-forge::tifffile=2026.3.3
  - pandas=2.3.3
  - conda-forge::beautifulsoup4=4.14.3
  - scikit-image=0.26.0
  - pip:
    - "BaSiCPy==2.0.0"
